### ISSUE TITLE
Gebruikt TFT display en instellingen

### ISSUE THREAD

**Issue by buckfast-beekeeper** [thieu-b55/Slimme-Digitale-Energie-Meter#5]
Beste Thieu,

Kan je vermelden welk type display je hebt gebruikt en de TFT_eSPI instellingen? Onzinnig een 480x320 display te gebruiken als het is ontworpen voor 320x240. Of omgekeerd gaat het niet passen. Portrait of landscape? Ik vermoed 480x320. 

Alvast bedankt.

Ik heb nog wel geen slimme meter maar die komt er sowieso. 

MQTT lijkt me een handige toevoeging. Ben je niet locatie gebonden en kunnen de verschillende ESP buiten elkaars bereik via het aanwezige WiFi netwerk communiceren of zelfs ver daarbuiten via de MQTT broker.

**Comment by thieu-b55** [comment]
LCD scherm te vinden bij aliexpress (staat ook vermeld in pdf file)
https://nl.aliexpress.com/item/32605410449.html?spm=a2g0o.order_list.0.0.21ef79d2ul1MHA&gatewayAdapt=glo2nld
Ik zou de AP (acces point, eigen netwerk) versie adviseren. Tot nu toe geen enkel probleem mee gehad. De STA versie (opgenomen in thuis netwerk) heeft enkel malen gefaald, maar misschien was mijn modem het probleem, die is ondertussen vervangen en sindsdien heb ik de STA versie niet meer geprobeerd.
Succes,
thieu

**Comment by buckfast-beekeeper** [comment]
In 480*320 gebruik ik [ILI9488 4"](https://nl.aliexpress.com/item/1005004152942022.html) schermen. SD connector standaard aanwezig. 

Vele ESP8266 en ESP32 in gebruik en eigenlijk geen problemen met de WiFi STA. 1 ervan is een 4" clock. Zelfs een storing in de communicatie ging gewoon voorbij zodra de router was herstart. Wat ook zelden voorkomt bij een Fritzbox.
